name: Presto

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/abraxas:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GCR
        run: echo $'${{ secrets.GCR_JSON_KEY }}' | docker login --username _json_key --password-stdin https://gcr.io

      - name: Pull the Old Layers
        run: docker pull $IMAGE_NAME

      - name: Build the Image
        run: docker build -t $IMAGE_NAME .

      - name: Push the Image
        run: docker push $IMAGE_NAME
